### ISSUE TITLE
FTP Timeout

### ISSUE THREAD

**Issue by marcosbis** [ldab/ESP32-CAM-Picture-Sharing#1]
Awesome stuff!.
is it possible to setup timeout or some way to limit the connection time on the FTP client?

**Comment by ldab** [comment]
That should not be a problem. Your server probably have a timeout already implemented.

Can you elaborate what you're trying to achieve a bit more?

**Comment by marcosbis** [comment]
I have an ESP32Cam on batteries taking a picture and send it via your FTP lib, then ESP32 go on deep sleep for 5minutes and repeat the sequence, If the FTP server is down for any reason the client never timeout then it will never trigger the sleep mode and it will consume the battery.  
Thanks

**Comment by ldab** [comment]
A timeout has been implemented on the last commit https://github.com/ldab/ESP32_FTPClient/issues/4#issuecomment-520074917

Soon, I'll improve it and return some confirmation which will prevent other commands of no connection.
