### ISSUE TITLE
I used your project for a 3d Scanner

### ISSUE THREAD

**Issue by Schaggo** [ldab/ESP32-CAM-Picture-Sharing#2]
Hey, just wanted to share, that I used your code for a photogrammetry project

https://github.com/Schaggo/ESP-3D-Scanner

Your work really helped me out! Thanks!

**Comment by ldab** [comment]
It looks very nice. Is 10 cameras enough for a highish res?

**Comment by Schaggo** [comment]
Here you can see the results:

https://imgur.com/gallery/LiceaAy

The resolution isn’t great, but I believe adding a couple of units will improve the overall model.
