### ISSUE TITLE
Adapting it to Arduino IDE

### ISSUE THREAD

**Issue by maxholgasson** [ldab/ESP32-CAM-Picture-Sharing#3]
Hi,
is it possible to adapt the code for the regular arduino IDE?

**Comment by ldab** [comment]
It is the same thing, just use the content of [/src/main.cpp](https://github.com/ldab/ESP32-CAM-Picture-Sharing/blob/master/src/main.cpp) on your *.ino file.

**Comment by maxholgasson** [comment]
Ok, got the error fatal error: BlynkSimpleEsp32.h: No such file or directory

Can I delete the Blynk part as I only need to upload to a ftp server?

**Comment by ldab** [comment]
> Ok, got the error fatal error: BlynkSimpleEsp32.h: No such file or directory

You're probably missing the Blynk library all together.



> Can I delete the Blynk part as I only need to upload to a ftp server?

Yes.

**Comment by maxholgasson** [comment]
Yes I dont have installed Blynk

**Comment by maxholgasson** [comment]
So I got it to upload but the camera is not detectded.
> [E][camera.c:1049] camera_probe(): Detected camera not supported.
[E][camera.c:1249] esp_camera_init(): Camera probe failed with error 0x20004

In other sketches I got the camera to work and needed to define the camera
>#define CAMERA_MODEL_AI_THINKER

is this also possible in your sketch?

**Comment by ldab** [comment]
This concept of ```#define CAMERA...``` is not present on my example, you need to manually insert it here, you can simply copy and paste your AI Thinker Pin definition to https://github.com/ldab/ESP32-CAM-Picture-Sharing/blob/61772acdebc3e0537e1b726e9dab13c5b19cf7f2/src/main.cpp#L98

The GitHub is used for issues tracking and not for helping with the code, please try different online forums for that type of question.

**Comment by maxholgasson** [comment]
Ok, but the error when using an camera is an issue

**Comment by ldab** [comment]
No, it's not. It is only a misusage of different libraries. You're mixing different libraries and expect it to work.
